### ISSUE TITLE
Installation failed on Ubuntu 22.04

### ISSUE THREAD

**Issue by woodbri** [meridionaljet/py3grads#4]
Trying to install on Ubuntu 22.04 and got the following:

`
woodbri@389F910:~/work/Py3GrADS$ sudo pip3 install git+https://github.com/meridionaljet/py3grads

Collecting git+https://github.com/meridionaljet/py3grads

  Cloning https://github.com/meridionaljet/py3grads to /tmp/pip-req-build-sjmbt9cs

  Running command git clone --filter=blob:none --quiet https://github.com/meridionaljet/py3grads /tmp/pip-req-build-sjmbt9cs

  Resolved https://github.com/meridionaljet/py3grads to commit 81dc3ce835b9e3fb18b7783883b06420392c8c3b

  Installing build dependencies ... done

  Getting requirements to build wheel ... done

  Preparing metadata (pyproject.toml) ... done

Building wheels for collected packages: UNKNOWN

  Building wheel for UNKNOWN (pyproject.toml) ... done

  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=961 sha256=362b460c14706ed0ae15ed244a4047ac600293f43c620be84c0d77e88f7a17dd

  Stored in directory: /tmp/pip-ephem-wheel-cache-t0tgnw9v/wheels/59/24/cd/e071be05253a151d60f619085c4a6ccbb1b1bf677fd1009411

Successfully built UNKNOWN

Installing collected packages: UNKNOWN

Successfully installed UNKNOWN-0.0.0

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
`
I also tried to install it as non-root user and got the same.
pip3 list shows
`UNKNOWN                0.0.0`

testing with

`#!/usr/bin/env python3

#from UNKNOWN import Grads
from py3grads import Grads
ga = Grads(verbose=False)
ga('open /home/woodbri/work/saltwatercentral/maps/wavecast/nam.ctl')
out, rc = ga('query file')
print(rc)
print(out)
`

and testing with

`woodbri@389F910:~/work/Py3GrADS$ python3 test.py
Traceback (most recent call last):
  File "/home/woodbri/work/Py3GrADS/test.py", line 4, in <module>
    from py3grads import Grads
ModuleNotFoundError: No module named 'py3grads'
`

and similarly

`woodbri@389F910:~/work/Py3GrADS$ python3 test.py
Traceback (most recent call last):
  File "/home/woodbri/work/Py3GrADS/test.py", line 3, in <module>
    from UNKNOWN import Grads
ModuleNotFoundError: No module named 'UNKNOWN'
`

**Comment by woodbri** [comment]
Currently grads is installed via apt:
`grads:amd64/jammy 3:2.2.1-4build1 uptodate`

**Comment by meridionaljet** [comment]
Hello, can you tell me the output of `pip3 --version`? The package name `UNKNOWN` in the output is indicative that `pip` is not handling the package metadata from `pyproject.toml` correctly, which could indicate it's an old version.

**Comment by woodbri** [comment]
`pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)`
